name = "ACiD"
uuid = "61bcfe73-0ff0-466d-b13c-3ec560fb4d71"
authors = ["Jakub Peleška", "Adrian Filcík", "Josef Weis"]
version = "1.0.0-DEV"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.10"
